# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 697c3e3222fc6c200d0c7bb8def53d546cd496a10daa380ab5d2f7739264a20179e3e1ee09fa0b2d25a1905e11f86d6d6933c5861db3aed5838b6e5eef1821fd

test:
  secret_key_base: 0fb4db168bf2b57dd911f9d9bff02bb0f840aeb146e77a4f0b01a3cba042e7ff1b61d62cb8520a15b16501ab87e023b407e21afb723c1ad28ef42e6a52832732

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
